name: CI / Python / Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  UV_VERSION: "0.5.5"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # skip if the PR is a draft
    if: github.event.pull_request.draft == false
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Install a specific version of uv.
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python using .python-version
        id: python
        uses: actions/setup-python@v5.2.0
        with:
          # don't have to supply, would auto resolve to this otherwise
          python-version-file: .python-version

      - name: Install Python dependencies
        if: steps.uv-cache.outputs.cache-hit != 'true'
        run: uv sync --dev --all-extras

      - name: Test with pytest
        run: uv run pytest

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python using .python-version
        id: python
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: .python-version

      - name: Install Python dependencies
        if: steps.uv-cache.outputs.cache-hit != 'true'
        run: uv sync --dev --all-extras

      - name: Run coverage
        run: uv run coverage run

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .coverage
          retention-days: 7
          include-hidden-files: true
          if-no-files-found: error

      - name: Report Coverage in Job Summary
        run: |
          uv run coverage report >> $GITHUB_STEP_SUMMARY
